# Generated by Django 4.2.1 on 2023-06-04 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=256)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', 'Unknown')], default='', max_length=1)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('industry', models.CharField(blank=True, default='', max_length=256)),
                ('salary', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000000000000.0)])),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
